#!/bin/bash -xe

TIMESTAMP=`date +"%Y%m%d%H%M%S"`
DATE=$(date +%d-%m-%Y" "%H:%M:%S)

DOCKER_REPO_NAME=${DOCKER_REPO_NAME}
DOCKER_REGISTRY_HOST=${DOCKER_REGISTRY_HOST}

TAG="${BUILD_NUMBER}-${GIT_COMMIT}"

env 

docker build \
  -t "$DOCKER_REPO_NAME:$TAG" \
  .

docker tag -f "$DOCKER_REPO_NAME:$TAG" "$DOCKER_REGISTRY_HOST/$DOCKER_REPO_NAME:$TAG"